### ISSUE TITLE
Still having large bit precision calculation issues

### ISSUE THREAD

**Issue by wjamesjr** [aleaxit/gmpy#522] opened 2024-10-14 17:01 UTC
When using mpfrs at high precision (> 2 ** 30 bits) algorithms fail.  I have verified that mpfr works as expected using a C++ wrapper and test pi agm code.  Using very similar code with gmpy, the code fails (agm fails to converge).  I am attaching some test code to demonstrate the problem.  At 250 million digits the agm routine works, at 400 million digits the agm routine fails to converge.  The c++ wrapper had a similar issue that was determined to be an argument in a call that needed to be a long that was an int.
[PiAGM_GMPY.py.zip](https://github.com/user-attachments/files/17367191/PiAGM_GMPY.py.zip)

**Comment by skirpichev** [comment] 2024-10-16 05:19
> Using very similar code with gmpy

Attached archive has only Python code.  We can't guess how "similar" it is to your C/C++ code.

**Comment by wjamesjr** [comment] 2024-10-16 05:35
C++ code is attached.
[main.cpp.zip](https://github.com/user-attachments/files/17389675/main.cpp.zip)

**Comment by skirpichev** [comment] 2024-10-16 06:06
Well, maybe I miss something else (versions use different variable name conventions, etc; it's not trivial to compare literally), but so far you code examples aren't "identical".  For example:
* to set precision you are using ``math.log(10) / math.log(2)`` coefficient, instead of more precise ``math.log2(10)``.  Either way it's not an equivalent of ``mpfr::digits2bits()``.
* you are using different initial values for ``y0``/``g``.  ``sqrt(0.5) != 1/sqrt(mpfr("2.0")``.
* finally, ``mpf("10.E-digits")`` != ``mpfr("10.0")**-digits``.

So, if you C++ code works correctly, please double check that Python code match it.

**Comment by wjamesjr** [comment] 2024-10-16 13:21
Made changes to Python source as suggested.  Still exhibits same issue with large bit precision.
[PiAGM_GMPY.py.zip](https://github.com/user-attachments/files/17396320/PiAGM_GMPY.py.zip)

**Comment by skirpichev** [comment] 2024-10-16 13:30
So far you just changed math.log(10) / math.log(2) to math.log2(10)

**Comment by wjamesjr** [comment] 2024-10-16 14:25
**bcf = math.log2(10)**

g, z, half = **sqrt(mpfr("0.5"))**, mpfr("0.25"), mpfr("0.5")

**epsilon = mpfr("10.E-" + str(needed_digits))**

The above three lines were changes.

**Comment by casevh** [comment] 2024-10-20 04:10
I have identified a bug in gmpy2. The new exponent limits assigned to a context are not being used to configure the MPFR library. The are currently only used when normalizing a final result.

The easy fix is to configure the MPFR library to used the maximum exponent on startup. The MPFR exponent range is thread local setting. So unilaterally change the value may impact other CPython applications (SageMATH) that may be running in the same thread.

The better option is saving the current exponent range, setting the new exponent range, calling MPFR, restoring the old exponent range.

I prefer the second option but it will be more complicated.

**Comment by wjamesjr** [comment] 2024-10-20 06:24
Glad to hear that you found a problem.  I am in no hurry for a solution, so take whatever time is needed to get it right.

**Comment by skirpichev** [comment] 2024-10-20 06:56
@wjamesjr, just to confirm, could you try the "easy fix"?

```diff
diff --git a/src/gmpy2_context.c b/src/gmpy2_context.c
index fecd79af..e4c776da 100644
--- a/src/gmpy2_context.c
+++ b/src/gmpy2_context.c
@@ -1034,6 +1034,7 @@ GMPy_CTXT_Set_emin(CTXT_Object *self, PyObject *value, void *closure)
         return -1;
     }
     self->ctx.emin = exp;
+    mpfr_set_emin(exp);
     return 0;
 }

@@ -1067,6 +1068,7 @@ GMPy_CTXT_Set_emax(CTXT_Object *self, PyObject *value, void *closure)
         return -1;
     }
     self->ctx.emax = exp;
+    mpfr_set_emax(exp);
     return 0;
 }

```

**Comment by wjamesjr** [comment] 2024-10-20 07:37
Sorry I have never built gmpy from source.  Always used pip.

**Comment by skirpichev** [comment] 2024-10-20 07:59
It's not too hard and documented:
https://gmpy2.readthedocs.io/en/latest/install.html#from-sources

Just apply the patch before doing ``pip install .``.

**Comment by wjamesjr** [comment] 2024-10-20 08:55
I tried to follow instructions and it timed out on my Mac.  See below:

Last login: Sun Oct 20 03:49:44 on ttys000
williamjames@Mac gmpy % git clone git://github.com/aleaxit/gmpy.git
Cloning into 'gmpy'...
fatal: unable to connect to github.com:
github.com[0: 140.82.112.3]: errno=Operation timed out

**Comment by skirpichev** [comment] 2024-10-20 09:23
Ah, perhaps it's some firewall settings on your side.  ``git clone https://github.com/aleaxit/gmpy.git`` - probably should work as you comment on the github.com.

**Comment by wjamesjr** [comment] 2024-10-20 11:22
Got it cloned and source change made now have an error on pip install:

williamjames@Mac gmpy % pip install -e .[tests]
zsh: no matches found: .[tests]

directory looks like:

COPYING		MANIFEST.in	demo		pyproject.toml	src
COPYING.LESSER	README.rst	docs		scripts		test
INSTALL		TODO		gmpy2		setup.py	test_cython

**Comment by skirpichev** [comment] 2024-10-20 11:43
On Sun, Oct 20, 2024 at 04:22:37AM -0700, Bill James wrote:
>    Got it cloned and source change made now have an error on pip install:
> 
>    ***@***.*** gmpy % pip install -e .[tests]
>    zsh: no matches found: .[tests]

You can do just ``pip install .``, this shouldn't trigger some
zsh-specific behaviour.

**Comment by wjamesjr** [comment] 2024-10-20 12:14
OK just pip install . worked but now 'gmp.h' can't be found .  gmp, mpfr and mpc are installed but since they were installed by home-brew they are installed in non-standard locations.  I ran into this before that stopped me from compiling open source packages.

**Comment by wjamesjr** [comment] 2024-10-20 13:23
Installed gmp, mpfr and libmpc with macports, pip install . still can't find gmp.h.

**Comment by skirpichev** [comment] 2024-10-21 02:52
Hmm, probably you can set correct CFLAGS and LDFLAGS like this:
```
PGMP="$(brew --prefix gmp)"
PMFR="$(brew --prefix mpfr)"
PMPC="$(brew --prefix libmpc)"
CFLAGS="-I$PGMP/include -I$PMFR/include -I$PMPC/include" LDFLAGS="-L$PGMP/lib -L$PMFR/lib -L$PMPC/lib" pip install .
```

**Comment by casevh** [comment] 2024-10-21 03:07
The current behavior of mpfr and mpc calculations involves two steps. The
first step uses the MPFR/MPC libraries to calculate the result to the
desired precision and the default exponent range. The default exponent
range is a thread-local (or global) setting in the MPFR library. The second
step extracts the exception flags and normalizes the result. During the
normalization step, gmpy2 temporarily changes the exponent range and then
restores the previous exponent range.

To keep the same behavior with 64 bit exponent range, we need to set the
exponent range used by the MFPR library to MPFR_EMAX_MAX and MPFR_EMIN_MIN.
This can be done by adding the following two lines to the startup code in
gmpy2.c:

 /* Set precision to maximum and minimum values. */
 mpfr_set_emax(MPFR_EMAX_MAX);
 mpfr_set_emin(MPFR_EMIN_MIN);

The default values in a context will still show the 30 bit default but that
is only used for normalization. Larger exponent ranges values will return
the expected values since the calculations use the maximum. It is trivial
to change GMPy_CTXT_New to use the expanded range but it is a user-visible
change.

I think gmpy2 shouldn't assume that the exponent values used by the MPFR
library don't change. This will require setting and restoring the exponent
setting for all calls into MFR/MPC. This will be a complex change.

For a bugfix release, I think setting the maximum exponent range is fine.
There should be no visible change and code that requests a larger exponent
range will "just work".

I don't have a strong opinion about changing the context defaults.

Eliminating the assumption that the underlying exponent range does not
change should  require a new version.

casevh

**Comment by wjamesjr** [comment] 2024-10-21 08:14
> @wjamesjr, just to confirm, could you try the "easy fix"?
> 
> ```diff
> diff --git a/src/gmpy2_context.c b/src/gmpy2_context.c
> index fecd79af..e4c776da 100644
> --- a/src/gmpy2_context.c
> +++ b/src/gmpy2_context.c
> @@ -1034,6 +1034,7 @@ GMPy_CTXT_Set_emin(CTXT_Object *self, PyObject *value, void *closure)
>          return -1;
>      }
>      self->ctx.emin = exp;
> +    mpfr_set_emin(exp);
>      return 0;
>  }
> 
> @@ -1067,6 +1068,7 @@ GMPy_CTXT_Set_emax(CTXT_Object *self, PyObject *value, void *closure)
>          return -1;
>      }
>      self->ctx.emax = exp;
> +    mpfr_set_emax(exp);
>      return 0;
>  }
> ```

I finally got the "easy fix" to build and tested it against the test case that I provided and it did not work for me.  That being said I am not confident that I have done everything right. Skirpichev, thank you for your patience, I can now build the latest version in the future if I need to.

Case, thank you for your explanation of a fix.  I wasn't expecting it to be this complicated.

**Comment by wjamesjr** [comment] 2024-10-22 01:06
Figured out what I was doing wrong.  I was running Python 3.13 interpreter and never using the modified code.  I had already backed out the "quick fix" change and changed to the two line addition to gmpy2.c when I figured this out.  Ran a test against the test code I submitted and using Python 3.11 it worked perfectly.   How can you modify the downloaded code to use 3.13 instead of 3.11?

**Comment by skirpichev** [comment] 2024-10-22 03:27
Usually it's a good idea to use virtual environments, especially if you are using different interpreter versions, work on different projects, etc.

E.g. after ``git clone ...gmpy.git && cd gmpy && patch the gmpy2_context.c``, do:
```
python3.13 -m venv .venv/3.13/  # create virtual environment
. .venv/3.13/bin/activate  # activate this virtual environment
pip install .  # install gmpy2 into this environment
python /path/to/PiAGM_GMPY.py  # run your script
```

**Comment by casevh** [comment] 2024-10-22 04:51
I created a branch called issue522. The resulting binaries can be found at https://github.com/aleaxit/gmpy/actions/runs/11452424995

Download the wheels.zip file at the bottom of the page and extract the appropriate version for you system. It can be installed with the command "python3.13 -m pip install gmpy2-2.2.1-cp313-cp313-macosx_11_0_arm64.whl". (I think that is correct version for you system.)

I've already tested the Windows version and it fails. The MPFR exponent type is defined as a C long so it is only 32 bits on Windows platform.

**Comment by wjamesjr** [comment] 2024-10-22 05:38
Tested against Python 3.11, 3.12, and 3.13 on arm64 Mac.  All three worked.

**Comment by casevh** [comment] 2024-10-22 14:19
Thanks for checking. I completed a successful test for 1_000_000_000 digits in slightly less than 2 hours. Now testing 2_000_000_000.

**Comment by wjamesjr** [comment] 2024-10-22 17:24
I am running into a problem now converting large mpfrs to a string.  It actually causes a Python crash.  I am now trying to find  the hard cutoff.  Suspect it is about 2**31 decimal digits (2147483648).  Working to verify it now.  Are you aware of a hard limit for max digits for mpfr to string conversions?

**Comment by skirpichev** [comment] 2024-10-22 17:46
What kind of "crash", have you seen some error message?  How you do conversion?  E.g. str/repr/format.

**Comment by wjamesjr** [comment] 2024-10-22 17:53
I am running it within PyCharm.  I get a popup window that says that Python quit unexpectedly.  I am attaching a simple test case that will demonstrate the problem.  It causes Python to quit on my Mac.
[test.py.zip](https://github.com/user-attachments/files/17480291/test.py.zip)

**Comment by wjamesjr** [comment] 2024-10-22 18:04
Error message is:

Process finished with exit code 139 (interrupted by signal 11:SIGSEGV)

Using str(mpfr) to convert.

**Comment by wjamesjr** [comment] 2024-10-23 00:18
Exit code 139 is a seg fault.  The conversion to a string is taking some time so it isn't happening immediately after start of conversion.  My guess is some code is writing beyond a memory buffer.

**Comment by skirpichev** [comment] 2024-10-23 03:31
> My guess is some code is writing beyond a memory buffer.

Can you try to reproduce this in C?  ``str(mpfr)`` internally just calls ``"{0:.pg}".format(mpfr)``, where
```c
p = (long)(log10(2) * (double)mpfr_get_prec(MPFR(self))) + 2;
```
which in turn calls ``mpfr_asprintf(ppbuf, "%.pRg", mpfr)``.

Looking on the code, I don't think problem is on our side:
https://github.com/aleaxit/gmpy/blob/17fb42d297193b1f7507c4e11a40204e7f03468d/src/gmpy2_convert_mpfr.c#L881
https://github.com/aleaxit/gmpy/blob/17fb42d297193b1f7507c4e11a40204e7f03468d/src/gmpy2_format.c#L202

**Comment by wjamesjr** [comment] 2024-10-23 09:46
> Looking on the code, I don't think problem is on our side:
> 

I agree.  The mpfr_asprintf call returns an int with the number of characters placed in the buffer.  int on my system is an int32.  So the call is incapable of returning a value greater than 2,147,483,647.  This is why 2,147,483,648 is failing for my test case.  I am guessing that the call is returning a negative value for number of characters written in this case.  The C++ wrapper that I was using checks for a negative return.


inline std::string mpreal::toString(const std::string& format) const
{
    char *s = NULL;
    std::string out;

    if( !format.empty() )
    {
        if(!(mpfr_asprintf(&s, format.c_str(), mpfr_srcptr()) < 0))
        {
            out = std::string(s);

            mpfr_free_str(s);
        }
    }

    return out;
}

So it looks like mpfr is not capable of converting mpfrs whose length is greater than 2,147,483,647.  It looks like the gmpy2 code does not check for a negative value and presses forward.  Is that an issue to fix.

**Comment by skirpichev** [comment] 2024-10-23 10:40
Good catch.  See https://github.com/aleaxit/gmpy/pull/526, I would appreciate testing (wheels could be downloaded at https://github.com/aleaxit/gmpy/actions/runs/11478047408?pr=526).

On another hand, e.g. on my system - INT_MAX is 2147483647, while gmpy2.get_max_precision() reports 9223372036854775551.  Perhaps, we should use the mpfr_out_str() (returns size_t) in str/repr instead.

**Comment by wjamesjr** [comment] 2024-10-23 13:58
> Good catch. See #526, I would appreciate testing (wheels could be downloaded at https://github.com/aleaxit/gmpy/actions/runs/11478047408?pr=526).

Tested against 2147483648 digit precision on Python 3.11, 3.12, 3.13 and received the message below:

Traceback (most recent call last):
  File "/Users/williamjames/PycharmProjects/stringtest/test.py", line 16, in <module>
    s1 = str(z)
RuntimeError: Number of characters written exceeds the INT_MAX

Tested against 2147483600 and got normal conversion.

mpfr_out_str() looks promising!

**Comment by wjamesjr** [comment] 2024-10-23 21:03
I did some testing to see if there is a  precision at the boundary from returning a string and throwing an exception.  Setting a precision of 2147483644 in my test script is the boundary and it still seg faults.  Maybe it is returning a zero versus a negative value??

**Comment by wjamesjr** [comment] 2024-10-24 00:41
mpfr_get_str writes directly to a string but separates the exponent into a separate variable.  It has size_t character size which makes it viable.  But I don't know how it can be a replacement for str() since the formatting is different.

**Comment by wjamesjr** [comment] 2024-10-24 02:23
The C++ wrapper for mpfr that I have been using has a toString() function that uses mpfr_asprintf() for mpfr version 2.4.0 + and mpfr_get_str for versions less than 2.4.0.  The code is below:

inline std::string mpreal::toString(int n, int b, mp_rnd_t mode) const
{
    // TODO: Add extended format specification (f, e, rounding mode) as it done in output operator
    (void)b;
    (void)mode;

#if (MPFR_VERSION >= MPFR_VERSION_NUM(2,4,0))

    std::ostringstream format;

    mp_prec_t digits = (n >= 0) ? n : 2 + bits2digits(mpfr_get_prec(mpfr_srcptr()));

    format << "%." << digits << "RNg";

    return toString(format.str());

#else

    char *s, *ns = NULL;
    size_t slen, nslen;
    mp_exp_t exp;
    std::string out;

    if(mpfr_inf_p(mp))
    {
        if(mpfr_sgn(mp)>0) return "+Inf";
        else               return "-Inf";
    }

    if(mpfr_zero_p(mp)) return "0";
    if(mpfr_nan_p(mp))  return "NaN";

    s  = mpfr_get_str(NULL, &exp, b, 0, mp, mode);
    ns = mpfr_get_str(NULL, &exp, b, (std::max)(0,n), mp, mode);

    if(s!=NULL && ns!=NULL)
    {
        slen  = strlen(s);
        nslen = strlen(ns);
        if(nslen<=slen)
        {
            mpfr_free_str(s);
            s = ns;
            slen = nslen;
        }
        else {
            mpfr_free_str(ns);
        }

        // Make human eye-friendly formatting if possible
        if (exp>0 && static_cast<size_t>(exp)<slen)
        {
            if(s[0]=='-')
            {
                // Remove zeros starting from right end
                char* ptr = s+slen-1;
                while (*ptr=='0' && ptr>s+exp) ptr--;

                if(ptr==s+exp) out = std::string(s,exp+1);
                else           out = std::string(s,exp+1)+'.'+std::string(s+exp+1,ptr-(s+exp+1)+1);

                //out = string(s,exp+1)+'.'+string(s+exp+1);
            }
            else
            {
                // Remove zeros starting from right end
                char* ptr = s+slen-1;
                while (*ptr=='0' && ptr>s+exp-1) ptr--;

                if(ptr==s+exp-1) out = std::string(s,exp);
                else             out = std::string(s,exp)+'.'+std::string(s+exp,ptr-(s+exp)+1);

                //out = string(s,exp)+'.'+string(s+exp);
            }

        }else{ // exp<0 || exp>slen
            if(s[0]=='-')
            {
                // Remove zeros starting from right end
                char* ptr = s+slen-1;
                while (*ptr=='0' && ptr>s+1) ptr--;

                if(ptr==s+1) out = std::string(s,2);
                else         out = std::string(s,2)+'.'+std::string(s+2,ptr-(s+2)+1);

                //out = string(s,2)+'.'+string(s+2);
            }
            else
            {
                // Remove zeros starting from right end
                char* ptr = s+slen-1;
                while (*ptr=='0' && ptr>s) ptr--;

                if(ptr==s) out = std::string(s,1);
                else       out = std::string(s,1)+'.'+std::string(s+1,ptr-(s+1)+1);

                //out = string(s,1)+'.'+string(s+1);
            }

            // Make final string
            if(--exp)
            {
                if(exp>0) out += "e+"+mpfr::toString<mp_exp_t>(exp,std::dec);
                else       out += "e"+mpfr::toString<mp_exp_t>(exp,std::dec);
            }
        }

        mpfr_free_str(s);
        return out;
    }else{
        return "conversion error!";
    }
#endif
}


I am commenting out the conditional if and testing the use of mpfr_get_str for mpfr version 2.4.0.

**Comment by wjamesjr** [comment] 2024-10-24 03:02
The C++ wrapper  http://www.holoborodko.com/pavel/mpfr/ that I have been testing has a toString() call.  It has a conditional if construct that uses mpfr_asprintf() for mpfr versions 2.4.0+ and mpfr_get_str for versions less than 2.4.0.  I am modifying the code to force the use of mpfr_get_str and see how well it works.

**Comment by casevh** [comment] 2024-10-24 05:56
I have some good news. I accidentally solved this issue years ago. 

The digits() method of an `mpfr` returns a tuple containing the digits in the mantissa, the exponent, and the precision. It calls `mpfr_get_str` which doesn't appear to have a size limit.

Maybe we just update some documentation and the error message in #526?

```
>>> from gmpy2 import *
>>> get_context().precision=8_500_000_000
>>> a=mpfr(1)/7
>>> b=a.digits()
>>> len(b[0])
2558754965
>>>
```

**Comment by skirpichev** [comment] 2024-10-24 07:59
> Setting a precision of 2147483644 in my test script is the boundary and it still seg faults.

Did you check error message, it has SIGSEGV?

Perhaps, you could try following C program and check it's behaviour near the limit:
<details>

```c
/* compile with cc a.c -lmpfr */
#include <stdio.h>
#include <stdlib.h>
#include <mpfr.h>
#include <math.h>
int main(int argc, char* argv[])
{
    mpfr_t x;
    mpfr_init_set_ui(x, 3, MPFR_RNDN);
    char *buf, fmt[20];
    long dps = INT_MAX + atoi(argv[1]);
    sprintf(fmt, "%%#.%ldRg", dps);

    int sz = mpfr_asprintf(&buf, fmt, x);
    if (sz != -1) {
//      printf("%s\n", buf);
        mpfr_free_str(buf);
    }

    mpfr_clear(x);
    return 0;
}
```

</details>
?

> The digits() method of an mpfr returns a tuple containing the digits in the mantissa, the exponent, and the precision. It calls mpfr_get_str which doesn't appear to have a size limit.

This doesn't fix str/repr.  On another hand, now I'm not sure that current str/repr is helpful for big precision.

> Maybe we just update some documentation and the error message in https://github.com/aleaxit/gmpy/pull/526?

What you suggest?

**Comment by wjamesjr** [comment] 2024-10-24 09:46
> Did you check error message, it has SIGSEGV?

I ran it again and the error message is different:

GNU MP: Cannot reallocate memory (old_size=2147487744 new_size=18446744071562067968)

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)

**Comment by wjamesjr** [comment] 2024-10-24 09:54
> I have some good news. I accidentally solved this issue years ago.
> 
> The digits() method of an `mpfr` returns a tuple containing the digits in the mantissa, the exponent, and the precision. It calls `mpfr_get_str` which doesn't appear to have a size limit.


The digits() method meets my requirement.

**Comment by skirpichev** [comment] 2024-10-24 09:59
> I ran it again and the error message is different:  GNU MP: Cannot reallocate memory

That's ok.  It means you run out of memory.  The GMP in such cases just calls abort() and we can't recover from this.  So, https://github.com/aleaxit/gmpy/pull/526 - seems to be working.

**Comment by wjamesjr** [comment] 2024-10-24 10:13
> > Maybe we just update some documentation and the error message in #526?
> 
> What you suggest?

What would the documentation change be? Maybe something like the below:

There are two methods of displaying mpfrs, str() and digits().  str() is most useful for smaller values and digits() for larger ones.   str() will fail for string lengths greater than about 2147483647.

**Closed** 2024-12-22 16:12 UTC
