### ISSUE TITLE
Memory leak in gmpy2_cache

### ISSUE THREAD

**Issue by thomaswucher** [aleaxit/gmpy#511] opened 2024-09-11 08:59 UTC
Thank you for providing gmpy2! While using it, I've noticed that my application consumes a lot of memory which seems to be never freed while using gmpy2 functionality. 

Doing a `git bisect`, the first bad commit seems to be 7351e2eb1abf4b37a47a822eb3f3f29f90c7f854. Versions older than that work fine, newer ones (including latest master) leak memory when creating gmpy2 objects.

The following minimal sample reproduces the issue:

```python
import gmpy2

while True:
    gmpy2.mpfr(0)
```

Running this example on my computer leaks around 100MB of memory per second, according to `htop`. Any help in fixing or working around this issue is highly appreciated.

**Comment by skirpichev** [comment] 2024-09-11 09:28
I can confirm issue.

Reproducer:
```
$ ulimit -v $((1024*128))
$ python
Python 3.12.5+ (heads/3.12:0181aa2e3e, Aug 29 2024, 14:55:08) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmpy2
>>> while True:
...     x = gmpy2.mpfr(0)
... 
GNU MP: Cannot allocate memory (size=16)
Aborted
```
Same happens for mpc, but not for mpz/mpq.  I'll take a look.

**Comment by skirpichev** [comment] 2024-09-11 10:39
Can't confirm it's https://github.com/aleaxit/gmpy/commit/7351e2eb1abf4b37a47a822eb3f3f29f90c7f854.  On 7351e2e^ I've same error.  In fact, looks like it affects 2.1.5 as well.

**Comment by casevh** [comment] 2024-09-12 05:19
I'm looking at the caching code. I fixed one error but it didn't fix the memory leak. Still looking....

**Comment by skirpichev** [comment] 2024-09-12 05:40
@casevh, could you confirm that problem is related to https://github.com/aleaxit/gmpy/commit/7351e2eb1abf4b37a47a822eb3f3f29f90c7f854?  I can't.

**Comment by skirpichev** [comment] 2024-09-13 01:43
Oh, probably I found issue, it's indeed https://github.com/aleaxit/gmpy/commit/7351e2eb1abf4b37a47a822eb3f3f29f90c7f854.

**Comment by skirpichev** [comment] 2024-09-13 01:59
PR is ready: https://github.com/aleaxit/gmpy/pull/512.

**Closed** 2024-09-13 03:46 UTC

**Comment by thomaswucher** [comment] 2024-09-13 11:08
Thank you for this fix. Using latest master, the test case posted above works fine now! Unfotunately, I found another memory leak, I will open another issue shortly.
