### ISSUE TITLE
mpfr: subnormalize=True breaks mpfr('inf') and mpfr('nan')

### ISSUE THREAD

**Issue by cdonovick** [aleaxit/gmpy#345] opened 2022-10-04 00:13 UTC
The following code snippet works:
```Python3
for v in ('inf', 'nan', float('inf'), float('nan')):
    with local_context(subnormalize=False): 
        gmpy.mpfr(v)

with local_context(subnormalize=True): 
   gmpy.mpfr(float('inf'))

with local_context(subnormalize=True): 
   gmpy.mpfr(float('nan'))
```

However these are broken:
```Python3
with local_context(subnormalize=True): 
   gmpy.mpfr('inf')

with local_context(subnormalize=True): 
   gmpy.mpfr('nan')
```
System information:
 Debian 5.19.6
 Python 3.10.7
 gmpy2 2.1.2 -- installed from pypi
 libgmp-dev 2:6.2.1+dfsg1-1
 libmpfr-dev 4.1.0-3
 libmpc-dev 1.2.1-2

**Comment by cdonovick** [comment] 2022-10-04 01:48
Today in new ways to fail writing a bug report:  not actually listing the failure.

The failing test cases raise `ValueError: invalid digits`

**Comment by casevh** [comment] 2022-10-04 03:55
I believe I've fixed this in the upcoming 2.1.3 release. Can you test the appropriate binary wheel contained in https://github.com/aleaxit/gmpy/suites/8231102535/artifacts/359235281 ?

**Comment by cdonovick** [comment] 2022-10-05 19:08
Ill be honest I have no Idea how to install a wheel directly. My bugs were fixed by installing gmpy2 master. I couldn't find a 2.1.3 tag or branch to install.

I do have a new bug though that is probably related.

Passing tests:
```Python3
with gmpy2.local_context(subnormalize=False): 
    assert gmpy2.is_signed(gmpy2.mpfr('-0'))

with gmpy2.local_context(subnormalize=False):
    assert gmpy2.is_signed(gmpy2.mpfr(float('-0')))

with gmpy2.local_context(subnormalize=True): 
    assert gmpy2.is_signed(gmpy2.mpfr(float('-0')))
```
Failing test:
```Python3
with gmpy2.local_context(subnormalize=True): 
    assert gmpy2.is_signed(gmpy2.mpfr('-0'))
```

If it is helpful in the passing test `repr(negative_zero) == "mpfr('-0.0')"`.
Where in the failing test   `repr(negative_zero) == "mpfr('0.0')"`.

**Comment by cdonovick** [comment] 2022-10-10 21:19
@casevh Would you expect the above to be solved in the 2.1.3 release

**Comment by casevh** [comment] 2022-10-11 05:04
Yes. I have identified the cause and fix will be committed soon.

**Comment by skirpichev** [comment] 2023-01-23 06:37
@casevh, probably this can be closed.

**Comment by casevh** [comment] 2023-01-24 05:33
Thanks for finding and reporting the bug.

Case

**Closed by casevh** 2023-01-24 05:33 UTC
